# Generated by Django 4.1.4 on 2022-12-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_course_certificate_course_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="preview",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
