# Generated by Django 4.1.4 on 2022-12-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_video_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="Certificate",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="preview",
            field=models.BooleanField(default=False),
        ),
    ]
